[general]
import = [
    "~/.config/alacritty/shell.toml",
    "~/.config/alacritty/colors.toml",
    "~/.config/alacritty/os-specific.toml"
]
live_config_reload = true

[font.normal]
family = "MesloLGS Nerd Font"

[cursor.style]
blinking = "never"

[mouse]
hide_when_typing = true

[window.dimensions]
columns = 125
lines = 30

[window.padding]
x = 5
y = 5
