#!/bin/bash
set -e
cd "$(dirname "$BASH_SOURCE")"

package=dotfiles
SETUP_DIR=~/.vim
. ../lib/setup.sh

# Undo files won't be created, unless the undo directory exists
[[ -d $SETUP_DIR/undodir ]] || mkdir -p $SETUP_DIR/undodir
# Same for .viminfo
[[ -d $SETUP_DIR/cache ]] || mkdir -p $SETUP_DIR/cache
link_files_in . -t $SETUP_DIR

# Read plugins, ignoring comments starting with " or #
for repo in $(grep -Ev '^["#]|^$' < plugins.vim); do
  plugin=$(basename $repo)

  if [[ ! -d "$SETUP_DIR/pack/$package/opt/$plugin" ]]; then
    $DOTFILES_SILENT ||
      echo Installing vim plugin: $plugin...
    git clone \
      --depth 1 \
      $($DOTFILES_VERBOSE || echo -q) \
      https://github.com/$repo \
      "$SETUP_DIR/pack/$package/opt/$plugin"
  fi
done
