syntax on

" Load opt plugins
for plugin in readfile(expand('~/.dotfiles/vim/opt-plugins.vim'))
    " Ignore comments
    if plugin =~ '^[^"]'
        let plugin = substitute(plugin, '.*/', '', '')
        exe 'packadd!' plugin
    endif
endfor

" Move .viminfo file
set viminfo=%,<800,'10,/50,:100,h,f0,n~/.vim/cache/.viminfo
"           | |    |   |   |    | |  + viminfo file path
"           | |    |   |   |    | + file marks 0-9,A-Z 0=NOT stored
"           | |    |   |   |    + disable 'hlsearch' loading viminfo
"           | |    |   |   + command-line history saved
"           | |    |   + search history saved
"           | |    + files marks saved
"           | + lines saved each register (old name for <, vi6.2)
"           + save/restore buffer list

" Scroll when over number of lines
set scrolloff=2

" Mouse support
" Drains a crazy amount of battery power if enabled
" set mouse=a

" Allow backspace
set backspace=indent,eol,start

" Tabs -> spaces
set expandtab

" Preserve words on wrap
set linebreak

" Indentation
set tabstop=4 softtabstop=4
set shiftwidth=4
set smartindent
set breakindent

" Window title
set title
set titlestring=%t%(\ %M%)%a\ -\ VIM

" Smart case-sensitive search
set smartcase

" Show line numbers relative to the current one
set number relativenumber

" Theme
colorscheme onedark

" Misc
set noswapfile
set nobackup
set undodir=~/.vim/undodir
set undofile
set incsearch

" No '-- INSERT --' in status line
set noshowmode

" Show partial command while typing it
set showcmd

" No ESC delay
set timeoutlen=1000 ttimeoutlen=0

" Change cursor shape on different mode
if empty($TMUX)
  " Vertical bar in insert mode
  let &t_SI = "\<Esc>]50;CursorShape=1\x7"
  " Block in normal mode
  let &t_EI = "\<Esc>]50;CursorShape=0\x7"
  " Underline in replace mode
  let &t_SR = "\<Esc>]50;CursorShape=2\x7"
else
  " Vertical bar in insert mode
  let &t_SI = "\e[5 q"
  " Block in normal mode
  let &t_SR = "\e[4 q"
  " Underline in replace mode
  let &t_EI = "\e[1 q"
endif

" Vim-airline settings
let g:airline_powerline_fonts = 1
let g:airline_theme = 'onedark'

" Enable buffers line
let g:airline#extensions#tabline#enabled = 1

" Use colorscheme cursorline color in normal and insert modes
let g:conoline_use_colorscheme_default_normal = 1
let g:conoline_use_colorscheme_default_insert = 1
