[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black =   "#676767"
blue =    "#00afff"
cyan =    "#5ffdff"
green =   "#5fdf67"
magenta = "#d75fdf"
red =     "#ff5f60"
white =   "#fffeff"
yellow =  "#fefb67"

[colors.normal]
black =   "#000000"
blue =    "#006fef"
cyan =    "#00c5c7"
green =   "#6fca67"
magenta = "#c930c7"
red =     "#ef4f50"
white =   "#d7d7d7"
yellow =  "#fad733"

[colors.primary]
background =     "#282c34"
dim_foreground = "#9a9a9a"
foreground =     "#d7d7d7"
