[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black =   "#676767"
blue =    "#4078f2"
cyan =    "#00bec2"
green =   "#50a14f"
magenta = "#c647c4"
red =     "#e45649"
white =   "#ffffff"
yellow =  "#c5a000"

[colors.normal]
black =   "#000000"
blue =    "#2058d2"
cyan =    "#00aeb2"
green =   "#31812f"
magenta = "#a627a4"
red =     "#ca1243"
white =   "#e7e7e7"
yellow =  "#a07c00"

[colors.primary]
background =     "#fafafa"
dim_foreground = "#d7d7d7"
foreground =     "#494b53"
