theme = "onedark"

[editor]
cursorline = true
line-number = "relative"
mouse = false
shell = ["bash", "-c"]
bufferline = "multiple"
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = true
wrap-indicator = "@ "

[editor.statusline]
right = ["diagnostics", "file-type", "selections", "register", "position", "file-encoding"]
mode.normal = "N"
mode.insert = "I"
mode.select = "V"
