exec 'source' . expand('~/.vim/vimrc')

" Indent with tabs on Unreal C++ sources
autocmd FileType cpp
  \ setlocal noexpandtab tabstop=4 shiftwidth=4

" Don't highlight types based on CamelCase, since Unreal conventions use it for everything
let g:cpp_custom_type_name_highlight = 0

function! s:UnrealHighlight() abort
  " Match Unreal custom CamelCase with prefix convention for types, like UClass, AActor, FStruct
  syn match UnrealType /\<[TUASICEF][A-Z]\w*[a-z]\w*\>\ze\([^:]\|:[^:]\|:$\|$\)/

  " Match custom int types
  syn match UnrealType /\<u\?int\(8\|16\|32\|64\)\>/

  hi def link UnrealType Type
endfunction

augroup unreal_cpp_highlight
  autocmd!
  autocmd Syntax c,cpp call s:UnrealHighlight()
augroup END
