# Load common rc
[[ ! -f ~/.shrc ]] || . ~/.shrc

PROMPT_COMMAND='set_terminal_title bash - $(basename "${PWD/$HOME/\~}")'

# Simple prompt
export PS1="$ "

# Show detailed prompt
p () {
    echo "[1;34m$(dirs +0)[0m $(git status &> /dev/null && echo 'on')[0;32m $(git branch --show-current 2> /dev/null)[0m"
}
