load_prompt_theme () {
    [[ -n "${1+set}" ]] || return 1

    local theme="$1"
    . "$ZSH/themes/$theme/$theme.zsh-theme"
}

load_plugins () {
    local repo
    for repo in $(grep -Ev '^#|^$' < "$ZSH/plugins.zsh"); do
        local plugin=$(basename $repo)
        . "$ZSH/plugins/$plugin/$plugin.plugin.zsh"
    done
}

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

ZSH="$ZDOTDIR"

# Load common rc
[[ ! -f ~/.shrc ]] || . ~/.shrc

HISTFILE="$ZSH/.zsh_history"
HISTSIZE=10000
SAVEHIST=10000
setopt appendhistory
# Don't save duplicates on history
setopt HIST_IGNORE_ALL_DUPS
# Don't show duplicates on history search
setopt HIST_FIND_NO_DUPS

# Enable history substring search with vi keybindings
bindkey -M vicmd 'k' history-beginning-search-backward
bindkey -M vicmd 'j' history-beginning-search-forward

load_prompt_theme powerlevel10k
load_plugins

# Load tab completions
autoload -Uz compinit && compinit

# To customize prompt, run `p10k configure` or edit .p10k.zsh.
[[ ! -f "$ZSH/.p10k.zsh" ]] || . "$ZSH/.p10k.zsh"
