# Load .bash_profile if never sourced
[[ ! ( "${BASH_PROFILE_SOURCED:-false}" = false && -f ~/.bash_profile ) ]] ||
  . ~/.bash_profile

# If not running interactively, don't do anything
[[ $- = *i* ]] || return

# Load common rc
[[ ! -f ~/.config/sh/shrc ]] || . ~/.config/sh/shrc

PROMPT_COMMAND='_prompt_command bash $?'
