# If .bash_profile has already been sourced do nothing
! ${BASH_PROFILE_SOURCED:-false} || return 0
export BASH_PROFILE_SOURCED=true

[[ ! -f ~/.config/sh/profile ]] || . ~/.config/sh/profile

# Silence deprecation warning on macOS
export BASH_SILENCE_DEPRECATION_WARNING=1

# Move history out of the home directory
export HISTFILE=$HOME/.cache/bash/bash_history
[[ -d ~/.cache/bash ]] || mkdir -p ~/.cache/bash

# Load bashrc on login shells
[[ ! -f ~/.bashrc ]] || . ~/.bashrc
